name: Solidity Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: cd hardhat && npm ci && cd ..

      - name: Run tests
        run:  
          cd hardhat && npx hardhat node &
          npx hardhat run scripts/deploy.ts --network localhost &&
          sleep 10 && 
          npx hardhat test --network localhost
